### PR TITLE
Support loading HFP configuration from file (#1)

### PR DESCRIPTION
**Pull request by henry434343**

### CODE REVIEW

**Comment by zxzxwu** [comment]
I think this doesn't need to be loaded in device? Passing a parameter to load in `examples/run_hfp_handsfree.py` is enough.

**Comment by henry434343** [comment]
> I think this doesn't need to be loaded in device? Passing a parameter to load in `examples/run_hfp_handsfree.py` is enough.

Since we would like to use the device directly in our application, passing parameters to examples might not fit our requirements. 
Might I know how can we determine which functions can be added to the device? Thanks for the help.

**Comment by barbibulle** [comment]
> > I think this doesn't need to be loaded in device? Passing a parameter to load in `examples/run_hfp_handsfree.py` is enough.
> 
> Since we would like to use the device directly in our application, passing parameters to examples might not fit our requirements. Do you have any suggestion? Thanks. Might I know how can we determine which functions can be added to the device? Thanks for the help.

I agree with @zxzxwu here. This config is an HFP-specific config, which the Device object doesn't use at all. It's only needed to instantiate a `HfProtocol` object (as is done in the HFP example app). If you want to pass a config file to `run_hfp_handsfree.py`, that code should be enhanced to allow parsing a config file (as you have done in this PR). If you're writing a different application, you would parse the config file from there. It may be useful to offer the JSON config file parsing function as a reusable helper, so that different apps could use the same method without having to re-implement that code. That function could therefore be located in `hfp.py`.

**Comment by henry434343** [comment]
> > > I think this doesn't need to be loaded in device? Passing a parameter to load in `examples/run_hfp_handsfree.py` is enough.
> > 
> > 
> > Since we would like to use the device directly in our application, passing parameters to examples might not fit our requirements. Do you have any suggestion? Thanks. Might I know how can we determine which functions can be added to the device? Thanks for the help.
> 
> I agree with @zxzxwu here. This config is an HFP-specific config, which the Device object doesn't use at all. It's only needed to instantiate a `HfProtocol` object (as is done in the HFP example app). If you want to pass a config file to `run_hfp_handsfree.py`, that code should be enhanced to allow parsing a config file (as you have done in this PR). If you're writing a different application, you would parse the config file from there. It may be useful to offer the JSON config file parsing function as a reusable helper, so that different apps could use the same method without having to re-implement that code. That function could therefore be located in `hfp.py`.

Thanks for the clarification. 
Could I keep the HFP configuration to the same device configuration, or do I need to use a separate HFP-specific config file to indicate the HFP feature?
For instance 
```
def from_config_file(config): # in hfp.py
    ...

configuration = hfp.from_config_file(sys.argv[1]) # in our application
```

**Comment by zxzxwu** [comment]
A question here is that, since HFP is not loaded by default, your application should have an entry for HFP, right?
If there is a customized entry point, could you modify there to take parameters?

**Comment by henry434343** [comment]
> A question here is that, since HFP is not loaded by default, your application should have an entry for HFP, right? If there is a customized entry point, could you modify there to take parameters?

Thanks for the clarification, will pass parameter from our entry point.

**Pull request closed without merging**
